<?php
/**
 * Title: Group (Media and Text Rows)
 * Slug: blockfolio/groupmediatext
 * Categories: blockfolio-patterns
 * Keywords: Group
 * Block Types: core/group
 */
?>
<!-- wp:spacer {"height":"50px"} --><div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div><!-- /wp:spacer -->
<!-- wp:media-text {"align":"full","mediaPosition":"right","mediaId":135,"mediaLink":"#","mediaType":"image","mediaWidth":30,"imageFill":false} --><div class="wp-block-media-text alignfull has-media-on-the-right is-stacked-on-mobile" style="grid-template-columns:auto 30%"><div class="wp-block-media-text__content"><!-- wp:heading {"level":1,"fontFamily":"instrument-serif"} --><h1 class="wp-block-heading has-instrument-serif-font-family">Hello, we are Blockfolio.</h1><!-- /wp:heading --><!-- wp:paragraph --><p>A block theme by Block Themes Pro.<br>Simple to setup. Easy on the eyes.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Say hello</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><figure class="wp-block-media-text__media"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/rectangle.png" alt="selective focus of man taking photo during daytime" class="wp-image-135 size-full"/></figure></div><!-- /wp:media-text -->
<!-- wp:spacer {"height":"50px"} --><div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div><!-- /wp:spacer -->
<!-- wp:media-text {"align":"full","mediaId":87,"mediaLink":"#","mediaType":"image","mediaWidth":40,"imageFill":false} --><div class="wp-block-media-text alignfull is-stacked-on-mobile" style="grid-template-columns:40% auto"><figure class="wp-block-media-text__media"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/rectangle.png" alt="frozen yellow Adidas Yeezy Boost v2's on white bedspread" class="wp-image-87 size-full"/></figure><div class="wp-block-media-text__content"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Small heading</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Bacon ipsum dolor amet jowl flank sausage boudin, pork belly salami pork chop tri-tip cupim beef andouille filet mignon buffalo bresaola drumstick. Beef tail chuck, frankfurter short ribs alcatra ham hock chicken drumstick salami corned beef.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Turducken turkey meatball hamburger andouille. Jerky fatback shank short loin t-bone. Tenderloin fatback drumstick pastrami. Meatloaf pork loin meatball leberkas. Pig leberkas swine ball tip ground round tenderloin kevin corned beef fatback pork ham jowl flank shank boudin. Jowl t-bone shankle boudin porchetta kevin fatback cupim. Hamburger bresaola kielbasa filet mignon chuck fatback short loin cupim.</p><!-- /wp:paragraph --></div></div><!-- /wp:media-text -->
<!-- wp:spacer {"height":"50px"} --><div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div><!-- /wp:spacer -->